### ISSUE TITLE
Use nagisa.wakati method

### ISSUE THREAD

**Issue by taishi-i** [Afoucaul/extracting-vocabulary-out-of-a-japanese-text#1]
Thanks for using nagisa library!
If you don't need to use part-of-speech tags in your code, please use `nagisa.wakati("今日はいい天気ですね")` method instead of using `nagisa.tagging("今日はいい天気ですね").words` to get a list of words.
It's more faster and simpler.

**Comment by Afoucaul** [comment]
Thank you very much, I'm glad you read my post :)
While I left my post untouched, I updated the code of the script on the associated repo.
Thanks again for your work, and stay up-to-date: I should be writing a follow-up in the next days.

❤

**Comment by taishi-i** [comment]
If you have troubles with using nagisa, we will answer your questions at any time.
Good luck!
